# Generated by Django 4.0.2 on 2022-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamcenter', '0002_saved_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundcloud_link',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_link',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube_link',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='saved',
            name='post_link',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='saved',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
